export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const SUBMIT_USER_SUCCESS = 'SUBMIT_USER_SUCCESS';
export const SUBMIT_USER_FAILURE = 'SUBMIT_USER_FAILURE';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_IS_SAVING = 'SET_IS_SAVING';